### ISSUE TITLE
Your pubspec.yaml file is broken.

### ISSUE THREAD

**Issue by radicaled** [playif/play_phaser#2]
This is what's in master right now:

``` yaml
dependencies:
  browser: ">=0.10.0+2 <0.11.0"
  uuid: ">=0.3.2 < 0.4.0"
  play_pixi:
    path: ../play_pixi
```

Won't work unless for some reason a package user has checked out play_pixi locally.
